development:
  adapter: mysql
  reconnect: false
  database: shortenurl
  pool: 5
  username: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: shortenurl_test
  pool: 5
  username: root
  host: localhost

